travis:
  secure:
    BINSTAR_TOKEN: eXRQyfMSOQYkRDu4U0/s/5EC9kNvPdgp4vytY+SBtfXyi9estU+crEcWTrsY4LfOXeGQq7QKj4m+Fun9X34iiLIf/soBTKQX4pu8bJ3aFg3yKcJmQV+a+ZQvW9Rxdl2sWDhh4Jr5yaohAj+cCzlnK1pVcVgOdeN7AeH5FoIxk50hhK7RQClMBU8eI0c/RCY8syonBCf6A8+mxD4kEIYGiWglTA6Jfkl3/Vzx0ffLAAi4+QK3RKEjYS3QzMBpwSdM9ARM6r18o7QSrc3RjqWjbVrE7Tz9IEbdtVkvYI5SD7Lceia/YIAUTWFPN3dI5+WHzWsgTi7zGMS/7FZUWdZei3ps451u2AhcKhJT8lxw5vbevmJHzUXKnOfjOqvPL+CjYSWMVJCectcgeh6bHzjUhcmsxYUJzFTLt/X7BiQAXCTXfC4RVFwCo10dqdgoezGLFy/WTvl2Bck3jcuC5cYusdzO8xI5JgAgZfXC9ngYAsPIV2bGj9K87JV2zst0crKxZGa0JpT/WIb+dtDMHj6pIO9BqPzOdYZUPWGLRRusyQN0f9TMzyMjaPPxo7zQCWew1kobDL/KAI6spRqPdsu2llPn/inV4RLVX/RIV7/N3hjUUT4+BRcH5Kg82u4Z9f+5nYDNslMCt9qwvKQaZeX2ynwHeVLZGy36R6HfXE8oiRM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
